function add_dict_vals!(d::Dict{String,String})
    for v ∈ values(d)
        get(d, v) do
            d[v] = v
        end
    end
end

const GLE_MARKERS = Dict{String,String}(
    "^"         => "triangle"   ,
    "△"         => "triangle"   ,
    "triangle"  => "triangle"   ,
    "wtriangle" => "wtriangle"  ,
    "ftriangle" => "ftriangle"  ,
    "s"         => "square"     ,
    "□"         => "square"     ,
    "square"    => "square"     ,
    "wsquare"   => "wsquare"    ,
    "fsquare"   => "fsquare"    ,
    "∘"         => "circle"     ,
    "o"         => "circle"     ,
    "circle"    => "circle"     ,
    "wcircle"   => "wcircle"    ,
    "•"         => "fcircle"    ,
    "fcircle"   => "fcircle"    ,
    "d"         => "diamond"    ,
    "diamond"   => "diamond"    ,
    "wdiamond"  => "wdiamond"   ,
    "fdiamond"  => "fdiamond"   ,
    "x"         => "cross"      ,
    "cross"     => "cross"      ,
    "+"         => "plus"       ,
    "plus"      => "plus"       ,
    "-"         => "minus"      ,
    "minus"     => "minus"      ,
    "*"         => "asterisk"   ,
    "asterisk"  => "asterisk"   ,
    "⊙"         => "odot"       ,
    "odot"      => "odot"       ,
    "⊖"         => "ominus"     ,
    "ominus"    => "ominus"     ,
    "⊕"         => "oplus"      ,
    "oplus"     => "oplus"      ,
    "⊗"         => "otimes"     ,
    "otimes"    => "otimes"     ,
    "⋆"         => "star"       ,
    "star"      => "star"       ,
    "star2"     => "star2"      ,
    "star3"     => "star3"      ,
    "star4"     => "star4"      ,
    "flower"    => "flower"     ,
    "♣"         => "club"       ,
    "♣"         => "club"       ,
    "club"      => "club"       ,
    "clubs"     => "club"       ,
    "♡"         => "heart"      ,
    "♥"         => "heart"      ,
    "❤"         => "heart"      ,
    "heart"     => "heart"      ,
    "hearts"    => "heart"      ,
    "♠"         => "spade"      ,
    "♠"         => "spade"      ,
    "spade"     => "spade"      ,
    "spades"    => "spade"      ,
    "†"         => "dag"        ,
    "dag"       => "dag"        ,
    "dagger"    => "dag"        ,
    "‡"         => "ddag"       ,
    "ddag"      => "ddag"       ,
    "ddagger"   => "ddag"       ,
    "§"         => "snake"      ,
    "snake"     => "snake"      ,
    )

const GLE_LSTYLES = Dict{String,Int}(
    "-"    => 0,
    "--"   => 9,
    "-."   => 8
    )

const GLE_TEXSCALE = ["scale", "fixed", "none"]

const GLE_FONTS = Dict{String,String}(
    "roman"                 => "rm"     ,
    "roman-bold"            => "rmb"    ,
    "roman-italic"          => "rmi"    ,
    "sans-serif"            => "ss"     ,
    "sans-serif-bold"       => "ssb"    ,
    "sans-serif-italic"     => "ssi"    ,
    "typewriter"            => "tt"     ,
    "typewriter-bold"       => "ttb"    ,
    "typewriter-italic"     => "tti"    ,
    "times"                 => "pstr"   ,
    "times-roman"           => "pstr"   ,
    "times-bold"            => "pstb"   ,
    "times-italic"          => "psti"   ,
    "times-bold-italic"     => "pstbi"  ,
    "courier"               => "psc"    ,
    "courier-bold"          => "pscb"   ,
    "courier-oblique"       => "psco"   ,
    "courier-bold-oblique"  => "pscbo"  ,
    "helvetica"                     => "psh"    ,
    "helvetica-bold"                => "pshb"   ,
    "helvetica-oblique"             => "psho"   ,
    "helvetica-bold-oblique"        => "pshbo"  ,
    "helvetica-narrow"              => "pshn"   ,
    "helvetica-narrow-bold"         => "pshnb"  ,
    "helvetica-narrow-oblique"      => "pshno"  ,
    "helvetica-narrow-bold-oblique" => "pshnbo" ,
    "avantgarde"                    => "psagb"  ,
    "avantgarde-book"               => "psagb"  ,
    "avantgarde-demi"               => "psagd"  ,
    "avantgarde-book-oblique"       => "psagbo" ,
    "avantgarde-demi-oblique"       => "psagdo" ,
    "bookman"               => "psbl"   ,
    "bookman-light"         => "psbl"   ,
    "bookman-demi"          => "psbd"   ,
    "bookman-light-italic"  => "psbli"  ,
    "bookman-demi-italic"   => "psbdi"  ,
    "newcentury"            => "psncsr" ,
    "newcentury-roman"      => "psncsr" ,
    "newcentury-bold"       => "psncsb" ,
    "newcentury-italic"     => "psncsi" ,
    "newcentury-bold-italic"=> "psncsbi",
    "palatino"              => "pspr"   ,
    "palatino-roman"        => "pspr"   ,
    "palantino-bold"        => "pspb"   ,
    "palatino-italic"       => "pspi"   ,
    "palatino-bold-italic"  => "pspbi"  ,
    "cmr"   => "texcmr"   ,
    "cmb"   => "texcmb"   ,
    "cmti"  => "texcmti"  ,
    "cmmi"  => "texcmmi"  ,
    "cmss"  => "texcmss"  ,
    "cmssb" => "texcmssb" ,
    "cmssi" => "texcmssi" ,
    "cmtt"  => "texcmtt"  ,
    "cmitt" => "texcmitt" ,
    "computer-modern-roman"             => "texcmr"  ,
    "computer-modern-bold"              => "texcmb"  ,
    "computer-modern-text-italic"       => "texcmti" ,
    "computer-modern-maths-italic"      => "texcmmi" ,
    "computer-modern-sans-serif"        => "texcmss" ,
    "computer-modern-sans-serif-bold"   => "texcmssb",
    "computer-modern-sans-serif-italic" => "texcmssi",
    "computer-modern-typewriter"        => "texcmtt" ,
    "computer-modern-italic-typewriter" => "texcmitt",
    )
add_dict_vals!(GLE_FONTS)

const GLE_LEGEND_POS = Dict{String,String}(
    "top-left"      => "tl",
    "bottom-left"   => "bl",
    "top-right"     => "tr",
    "bottom-right"  => "br",
    "top-center"    => "tc",
    "bottom-center" => "bc",
    "left-center"   => "lc",
    "right-center"  => "rc",
    "center"        => "cc",
    )
add_dict_vals!(GLE_LEGEND_POS)
